// Everything in the shop, best first and worst last. Better things are cheap
// because people just take them. Worse things cost more because almost
// everybody doubles them, so the pile gets enormous before anyone says yes.
export interface Thing {
  id: string;
  name: string;
  plural: string;
  price: bigint;
  // Out of 100: how likely a person is to say "double it".
  doubleChance: number;
  colors: Record<string, string>;
  sprite: string[];
}

export const THINGS: Thing[] = [
  {
    id: "diamond",
    name: "Diamond",
    plural: "Diamonds",
    price: 0n,
    doubleChance: 1,
    colors: { c: "#2a9fd6", C: "#8fe6ff", w: "#ffffff" },
    sprite: [
      "..........",
      "..cccccc..",
      ".cCCwCCCc.",
      "cCCwCCCCCc",
      "cccccccccc",
      ".cCCCCCCc.",
      "..cCCCCc..",
      "...cCCc...",
      "....cc....",
      "..........",
    ],
  },
  {
    id: "emerald",
    name: "Emerald",
    plural: "Emeralds",
    price: 5n,
    doubleChance: 5,
    colors: { g: "#138a3c", G: "#3fe07a", w: "#d9ffe6" },
    sprite: [
      "..........",
      "...gggg...",
      "..gGGGGg..",
      ".gGGwGGGg.",
      ".gGwGGGGg.",
      ".gGGGGGGg.",
      ".gGGGGGGg.",
      "..gGGGGg..",
      "...gggg...",
      "..........",
    ],
  },
  {
    id: "gold",
    name: "Gold Bar",
    plural: "Gold Bars",
    price: 15n,
    doubleChance: 10,
    colors: { y: "#ffcf2e", Y: "#fff08a", o: "#b37700" },
    sprite: [
      "..........",
      "..........",
      "...yyyyy..",
      "..yYYYYYy.",
      ".yYYYYYYyo",
      "yyyyyyyyoo",
      "yyyyyyyyoo",
      "ooooooooo.",
      "..........",
      "..........",
    ],
  },
  {
    id: "iron",
    name: "Iron Bar",
    plural: "Iron Bars",
    price: 30n,
    doubleChance: 20,
    colors: { y: "#a9adb5", Y: "#e3e6eb", o: "#5f636b" },
    sprite: [
      "..........",
      "..........",
      "...yyyyy..",
      "..yYYYYYy.",
      ".yYYYYYYyo",
      "yyyyyyyyoo",
      "yyyyyyyyoo",
      "ooooooooo.",
      "..........",
      "..........",
    ],
  },
  {
    id: "coal",
    name: "Coal",
    plural: "Coal",
    price: 60n,
    doubleChance: 30,
    colors: { k: "#1c1c22", K: "#55555f" },
    sprite: [
      "..........",
      "..........",
      "...kkkk...",
      "..kKkkkk..",
      ".kkkkKkkk.",
      ".kKkkkkkk.",
      "kkkkkkKkkk",
      ".kkkkkkkk.",
      "..........",
      "..........",
    ],
  },
  {
    id: "sofa",
    name: "Sofa",
    plural: "Sofas",
    price: 120n,
    doubleChance: 40,
    colors: { r: "#b0303f", R: "#e0566a", b: "#4a2a14" },
    sprite: [
      "..........",
      "..........",
      ".rrrrrrrr.",
      ".rRRRRRRr.",
      "rrRRRRRRrr",
      "rrrrrrrrrr",
      "rrrrrrrrrr",
      "rrrrrrrrrr",
      ".b......b.",
      "..........",
    ],
  },
  {
    id: "computer",
    name: "Vintage Computer from 1989",
    plural: "Vintage Computers from 1989",
    price: 300n,
    doubleChance: 50,
    colors: { b: "#d8cfb0", d: "#8f866a", k: "#1d2a1d", g: "#5dff7a" },
    sprite: [
      ".bbbbbbbb.",
      ".bkkkkkkb.",
      ".bkgggkkb.",
      ".bkgkkkkb.",
      ".bkkkkkkb.",
      ".bbbbbbbb.",
      "..dddddd..",
      "bbbbbbbbbb",
      "bdbdbdbdbb",
      "bbbbbbbbbb",
    ],
  },
  {
    id: "sizzles",
    name: "Sizzles",
    plural: "Sizzles",
    price: 750n,
    doubleChance: 60,
    colors: { w: "#d8d8e0", r: "#b8322a", p: "#ffb3a0" },
    sprite: [
      "..........",
      ".w..w..w..",
      "..w..w..w.",
      ".w..w..w..",
      "..........",
      "rrpprrpprr",
      "pprrpprrpp",
      "rrpprrpprr",
      "..........",
      "..........",
    ],
  },
  {
    id: "chair",
    name: "Chair",
    plural: "Chairs",
    price: 2_000n,
    doubleChance: 70,
    colors: { b: "#7a4a22", B: "#a8703a" },
    sprite: [
      "..b.......",
      "..b.......",
      "..bBBB....",
      "..b.......",
      "..bBBB....",
      "..b.......",
      "..bbbbbbb.",
      "..b.....b.",
      "..b.....b.",
      "..b.....b.",
    ],
  },
  {
    id: "card",
    name: "Thanksgiving Card",
    plural: "Thanksgiving Cards",
    price: 6_000n,
    doubleChance: 78,
    colors: { o: "#d9731f", y: "#ffe9b8", r: "#c9302c", g: "#e8a21a", b: "#6b3d1a", d: "#ff9a1f" },
    sprite: [
      "oooooooooo",
      "oyyyyyyyyo",
      "oyrogoryyo",
      "oyorbbroyo",
      "oyybbbbyyo",
      "oyybbbbyyo",
      "oyyyddyyyo",
      "oyyyyyyyyo",
      "oooooooooo",
      "..........",
    ],
  },
  {
    id: "balloon",
    name: "Balloon",
    plural: "Balloons",
    price: 25_000n,
    doubleChance: 85,
    colors: { r: "#e8323c", R: "#ff9aa0", s: "#d8d8e0" },
    sprite: [
      "...rrrr...",
      "..rRrrrr..",
      ".rRrrrrrr.",
      ".rrrrrrrr.",
      ".rrrrrrrr.",
      "..rrrrrr..",
      "...rrrr...",
      "....rr....",
      ".....s....",
      "....s.....",
    ],
  },
  {
    id: "paper",
    name: "Piece of Paper",
    plural: "Pieces of Paper",
    price: 200_000n,
    doubleChance: 90,
    colors: { w: "#f4f4ee", l: "#8fb4e8" },
    sprite: [
      "..wwwwww..",
      "..wwwwwww.",
      "..wlllllw.",
      "..wwwwwww.",
      "..wlllllw.",
      "..wwwwwww.",
      "..wllllww.",
      "..wwwwwww.",
      "..wwwwwww.",
      "..........",
    ],
  },
  {
    id: "pencil",
    name: "Pencil",
    plural: "Pencils",
    price: 5_000_000n,
    doubleChance: 94,
    colors: { p: "#ff8fb0", m: "#b0b0b8", y: "#ffd23a", Y: "#ffe98a", s: "#e8c08a", k: "#2a2a2a" },
    sprite: [
      "..........",
      "..........",
      "..........",
      "pmyyyyyss.",
      "pmYYYYYssk",
      "pmyyyyyss.",
      "..........",
      "..........",
      "..........",
      "..........",
    ],
  },
  {
    id: "eraser",
    name: "Eraser",
    plural: "Erasers",
    price: 1_000_000_000n,
    doubleChance: 97,
    colors: { p: "#ff8fb0", P: "#ffc4d6", d: "#d9607f" },
    sprite: [
      "..........",
      "..........",
      "..........",
      "...pppppp.",
      "..pPPPPppd",
      ".ppppppppd",
      ".pppppppdd",
      ".dddddddd.",
      "..........",
      "..........",
    ],
  },
  {
    id: "dirt",
    name: "Dirt",
    plural: "Dirt",
    price: 2028240960365167000000000000000n,
    doubleChance: 99,
    colors: { d: "#6b4423", D: "#8a5a32", k: "#3d2512" },
    sprite: [
      "..........",
      "..........",
      "..........",
      "..........",
      "....dd....",
      "..dDddkd..",
      ".dkddDddd.",
      "ddddkdddDd",
      "kkkkkkkkkk",
      "..........",
    ],
  },
];

export function drawThing(context: CanvasRenderingContext2D, thing: Thing, x: number, y: number, pixel: number): void {
  thing.sprite.forEach((row, rowIndex) => {
    [...row].forEach((key, columnIndex) => {
      const color = thing.colors[key];
      if (!color) return;
      context.fillStyle = color;
      context.fillRect(x + columnIndex * pixel, y + rowIndex * pixel, pixel, pixel);
    });
  });
}
