import { sprite, type Choice } from "./sprites";

// Bosses. Far bigger than anything else in the world, far harder to put down,
// and each with one thing it does that nothing else does.

// Oscar's own drawing, in pixels. The paper it came from is in
// art/oscar-bot-drawing.heic, next door. A huge empty screen of a body with one small
// furious face up in it — V eyebrows, two hatched eyes, a long gritted mouth —
// a crack down one wall and a staircase up the other. Off the top: a burning
// torch, a hand pointing up, an aerial, and a sign that says RUN. Two striped
// tentacles curl down the back, a buzzsaw hangs off one side on a jointed arm,
// a propeller spins underneath, and the hypnosis spiral swings from a chain.
// It stands on two thin legs that meet in a V. Labelled, on the paper: TOO BIG.
// Two frames: the fire flickers, the saw turns, the spiral winds, the tentacles
// ripple.
const OSCAR_BOT_FRAME_1 = `
  ..........................................................
  ....y...............kk....................................
  ...yoy..............kk...........kkkkkkkkkkkkkkkkk........
  ..yooo..............kk...........kwwwwwwwwwwwwwwwk........
  ...oo.y.............kk...........kwrrrwrwrwrwwrwwk........
  ..oooo..........kkkkk............kwrwrwrwrwrrwrwwk........
  ..kkkkkk........kwwwk.......kkk..kwrrrwrwrwrwrrwwk........
  ..kkkkkk........kwwwk.......kkk..kwrrwwrwrwrwwrwwk........
  .....kk.........kkkkk.......kkk..kwrwrwrrrwrwwrwwk........
  .....kk.........kkkk........k.k..kkkkkkkkkkkkkkkkk........
  ......kkk.......kwwk.......k...k........kk................
  ......kwk.......kkkk.......kkkkk........kk.....kk.........
  ......kkkk.......kk.......k.....k......kkkk....kkkk.......
  .........kk......kk.....kkk.....kkk....kkkk...wwwkkk......
  .........kk......kk.....kkk.....kkk.....kk....kwkkkkk.....
  ..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwkk....
  ..........kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkwwwkk...
  ..........kwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwk..kkwkkk...
  ..........kwkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkwk...kkkkkk..
  ..........kwkwwkkkwwwwwwwwwwwwwwwwwwwwwwwwwwkwk....kkkwk..
  ..........kwkwwwkkwwwwwwwwwwwwwwwwwwwwwwwwwwkwk....kkwwkk.
  ..........kwkwwkkwwwkkwwwwwwwwwwwwwkkwwwwwwwkwk.....kkwwk.
  ..........kwkwwwkkwwwkkwwwwwwwwwwwkkwwwwwwwwkwk......kkkk.
  ..........kwkwwkkwwwwwkkwwwwwwwwwkkwwwwwwwwwkwkkkk...kkkk.
  ..........kwkwwwkkwwwwwkkwwwwwwwkkwwwwwwwwwwkwkkkkk..kkkk.
  ..........kwkwwkkwwwwwwwkkwwwwwkkwwwwwwwwwwwkwkkwkkk.kkwkk
  ..........kwkwkwkkwwwwwwwwwwwwwwwwwwwwwwwwwwkwkkkkkk.kkwkk
  ..........kwkwwwwwwwwkkkkwwwwwwwkkkkwwwwwwwwkwk.kkkkkkkwkk
  ..........kwkwwwwwwwwkkwkwwwwwwwkkwkwwwwwwwwkwk..kkkk.kkkk
  ..........kwkwwwwwwwwkwkkwwwwwwwkwkkwwwwwwwwkwk...kkk.kkkk
  ..........kwkwwwwwwwwkkkkwwwwwwwkkkkwwwwwwwwkwk...kkkkkwkk
  .........kkwkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkwk...kkkkkwk.
  ....kkkkkkkwkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkwk..kkkkkkwk.
  ....kwkkk.kwkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkwk..kwk.kkkk.
  ....kwk...kwkwwwwwwwkkkkkkkkkkkkkkkkkwwwwwkwkwk.kkkk.kkkk.
  ....kkk...kwkwwwwwwwkwkwkwkwkwkwkwkwkwwwkkkwkwk.kkk.kkkkk.
  ....kk....kwkwwwwwwwkwkwkwkwkwkwkwkwkwwwkwwwkwkkkkk.kkwk..
  ....kk....kwkwwwwwwwkkkkkkkkkkkkkkkkkwkkkwwwkkkkkk.kkwkk..
  ...kk.....kwkwwwwwwwwwwwwwwwwwwwwwwwwwkwwwwwkwkkk..kkkk...
  ..kkkk....kwkwwwwwwwwwwwwwwwwwwwwwwwkkkwwwwwkwkk..kkkkk...
  ..kwwk....kwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwk..kkkkk....
  ..kkkk....kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.kkkkk.....
  ...kk.....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..kkkk.....
  ....kk.k............kkk...........kkk....kk......kk.......
  .....kkG......k.......kk.........kk......kk...............
  ...k.GGGGG.k..kk.......kk.......kk.......kv...............
  ....GGGGGGG....kkk......kk.....kk.......vwwwv.............
  ....GGGwGGG....kwkkkk...kk.....kk......vwvvvwv............
  ...GGGwwwGGG...kkk..k....kk...kk.......wvwwwww............
  ..k.GGGwGGG.k..k..........kk.kk.......vwvwwvwvv...........
  ....GGGGGGG...k............kkk.........vwvwvwv............
  .....GGGGG....k............kkk.........vvwwwvv............
  ....k..G.k.................kkk..........vvvvv.............
  ..........................................v...............
`;

const OSCAR_BOT_FRAME_2 = `
  ..........................................................
  ...y................kk....................................
  ...yo.y.............kk...........kkkkkkkkkkkkkkkkk........
  ...ooy..............kk...........kwwwwwwwwwwwwwwwk........
  ..yooo..............kk...........kwrrrwrwrwrwwrwwk........
  ...ooo..........kkkkk............kwrwrwrwrwrrwrwwk........
  ..kkkkkk........kwwwk.......kkk..kwrrrwrwrwrwrrwwk........
  ..kkkkkk........kwwwk.......kkk..kwrrwwrwrwrwwrwwk........
  .....kk.........kkkkk.......kkk..kwrwrwrrrwrwwrwwk........
  .....kk.........kkkk........k.k..kkkkkkkkkkkkkkkkk........
  ......kkk.......kwwk.......k...k........kk................
  ......kwk.......kkkk.......kkkkk........kk.....kk.........
  ......kkkk.......kk.......k.....k......kkkk....kkkk.......
  .........kk......kk.....kkk.....kkk....kkkk...kkkwkk......
  .........kk......kk.....kkk.....kkk.....kk....kkwwwkk.....
  ..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwkkk....
  ..........kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkk...
  ..........kwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwk..kkkwkk...
  ..........kwkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkwk...kkwwkk..
  ..........kwkwwkkkwwwwwwwwwwwwwwwwwwwwwwwwwwkwk....kkwkk..
  ..........kwkwwwkkwwwwwwwwwwwwwwwwwwwwwwwwwwkwk....kkkkkk.
  ..........kwkwwkkwwwkkwwwwwwwwwwwwwkkwwwwwwwkwk.....kkkkk.
  ..........kwkwwwkkwwwkkwwwwwwwwwwwkkwwwwwwwwkwk......kwwk.
  ..........kwkwwkkwwwwwkkwwwwwwwwwkkwwwwwwwwwkwkkkk...kwwk.
  ..........kwkwwwkkwwwwwkkwwwwwwwkkwwwwwwwwwwkwwwkkk..kkwk.
  ..........kwkwwkkwwwwwwwkkwwwwwkkwwwwwwwwwwwkwkkkkkk.kkkkk
  ..........kwkwkwkkwwwwwwwwwwwwwwwwwwwwwwwwwwkwkkkkkk.kkkkk
  ..........kwkwwwwwwwwkkkkwwwwwwwkkkkwwwwwwwwkwk.kkwkkkkkkk
  ..........kwkwwwwwwwwkkwkwwwwwwwkkwkwwwwwwwwkwk..kkkk.kwkk
  ..........kwkwwwwwwwwkwkkwwwwwwwkwkkwwwwwwwwkwk...kwk.kwkk
  ..........kwkwwwwwwwwkkkkwwwwwwwkkkkwwwwwwwwkwk...kkkkkkkk
  .........kkwkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkwk...kwkkkkk.
  ....kkkkkkkwkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkwk..kkkkkkkk.
  ....kwkkk.kwkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkwk..kkk.kkwk.
  ....kwk...kwkwwwwwwwkkkkkkkkkkkkkkkkkwwwwwkwkwk.kkkk.kwkk.
  ....kkk...kwkwwwwwwwkwkwkwkwkwkwkwkwkwwwkkkwkwk.kkk.kkwkk.
  ....kk....kwkwwwwwwwkwkwkwkwkwkwkwkwkwwwkwwwkwkkkkk.kkkk..
  ....kk....kwkwwwwwwwkkkkkkkkkkkkkkkkkwkkkwwwkkkkkk.kkkkk..
  ...kk.....kwkwwwwwwwwwwwwwwwwwwwwwwwwwkwwwwwkwkkk..kkwk...
  ..kkkk....kwkwwwwwwwwwwwwwwwwwwwwwwwkkkwwwwwkwkk..kkwkk...
  ..kwwk....kwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwk..kkkkk....
  ..kkkk....kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.kkkkk.....
  ...kk.....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..kkkk.....
  ....kk...k..........kkk...........kkk....kk......kk.......
  .....kkG.........k....kk.........kk......kk...............
  .....GGGGG.......k.....kk.......kk.......kv...............
  ..k.GGGGGGG.k..kkk......kk.....kk.......vwwwv.............
  ....GGGwGGG.kkkkwk......kk.....kk......vwvvvwv............
  ...GGGwwwGGGk..kkk.......kk...kk.......wvwwwvw............
  ....GGGwGGG.......k.......kk.kk.......vwvwwwwwv...........
  ....GGGGGGG.......k........kkk.........vwvvvwv............
  ...k.GGGGG.k...............kkk.........vvwwwvv............
  .......G...................kkk..........vvvvv.............
  .......k..................................v...............
`;

// The cube. Spikes on top, a face on the front, and absolutely no brakes.
const GEOMETRY_DASH_ART = `
  ..k...k...k..
  .kkk.kkk.kkk.
  kkkkkkkkkkkkk
  uuuuuuuuuuuuu
  ucccucccucccu
  ukkkukkkukkku
  uuuuuuuuuuuuu
  uukkuuuuukkuu
  uukkuuuuukkuu
  uuuuuuuuuuuuu
  uuukkkkkkkuuu
  uuuuuuuuuuuuu
  .uuuuuuuuuuu.
`;

export const BOSSES: Choice[] = [
  { id: "oscar-bot", name: "The O.S.C.A.R. BOT", habitat: "land", sprite: sprite(OSCAR_BOT_FRAME_1, OSCAR_BOT_FRAME_2) },
  { id: "geometry-dash", name: "Geometry Dash", habitat: "land", sprite: sprite(GEOMETRY_DASH_ART) },
];

export const BOSS_IDS = new Set(BOSSES.map((b) => b.id));

// How much of a beating a boss takes before it goes down.
export const BOSS_HP: Record<string, number> = {
  "oscar-bot": 250,
  "geometry-dash": 180,
};

export const isBoss = (type: string): boolean => BOSS_IDS.has(type);
